AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  DeployUserName:
    Type: String
  DeployBucketName:
    Type: String
Resources:
  DeployBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Ref DeployBucketName
      AccessControl: Private
  DeployUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref DeployUserName
      Policies:
        - PolicyName: readwrite-deploy-bucket
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
                - s3:*
              Resource:
                - !Sub "arn:aws:s3:::${DeployBucketName}"
                - !Sub "arn:aws:s3:::${DeployBucketName}/*"
  AccessKey:
    Type: AWS::IAM::AccessKey
    DependsOn: DeployUser
    Properties:
      UserName: !Ref DeployUserName
Outputs:
  AccessKey:
    Value: !Ref AccessKey
  Secret:
    Value: !GetAtt AccessKey.SecretAccessKey
